### ISSUE TITLE
Docker Compose file

### ISSUE THREAD

**Issue by nitschis** [DialmasterOrg/Youtarr#62]
Could you provide a docker-compose.yml file? I have tried, but I just can't get it to work.
Thank you.

**Comment by dialmaster** [comment]
Everything runs in a single container -- there should be no need for a
docker-compose file.
What did you try, and what happened when you did? Can you cut and paste the
command line output?

Thanks,
Chris

**Comment by nitschis** [comment]
Thank you very much for your reply. I would like to use persistent storage (mounted locally) and make it easy to move to other servers.

The container is just contantly restarting.

This is my docker-compose.yml:
```
  youtarr:
    container_name: youtarr
    image: dialmaster/youtarr
    ports:
      - "3011:3011"
      - "3321:3321"
    volumes:
      - "/home/user/.config/appdata/youtarr/mariadb:/var/lib/mysql"
      - "/home/user/.config/appdata/youtarr/app:/app"
      - /mnt/rclone/TV/TV_Shows_YT:/tv_shows
    restart: unless-stopped

```

I get this error:
```
Waiting for DB...
Waiting for DB...
.230910 03:05:49 mysqld_safe Logging to syslog.
230910 03:05:49 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
internal/modules/cjs/loader.js:934
  throw err;
  ^

Error: Cannot find module '/app/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Waiting for DB...
Waiting for DB...
.230910 03:05:51 mysqld_safe Logging to syslog.
230910 03:05:51 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
internal/modules/cjs/loader.js:934
  throw err;
  ^

Error: Cannot find module '/app/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Waiting for DB...
Waiting for DB...
.230910 03:05:53 mysqld_safe Logging to syslog.
230910 03:05:53 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
internal/modules/cjs/loader.js:934
  throw err;
  ^

Error: Cannot find module '/app/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Waiting for DB...
Waiting for DB...
.230910 03:05:55 mysqld_safe Logging to syslog.
230910 03:05:55 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
internal/modules/cjs/loader.js:934
  throw err;
  ^

Error: Cannot find module '/app/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Waiting for DB...
Waiting for DB...
.230910 03:05:57 mysqld_safe Logging to syslog.
230910 03:05:57 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
internal/modules/cjs/loader.js:934
  throw err;
  ^

Error: Cannot find module '/app/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Waiting for DB...
Waiting for DB...
.230910 03:06:00 mysqld_safe Logging to syslog.
230910 03:06:00 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
internal/modules/cjs/loader.js:934
  throw err;
  ^

Error: Cannot find module '/app/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Waiting for DB...
Waiting for DB...
.230910 03:06:05 mysqld_safe Logging to syslog.
230910 03:06:05 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
internal/modules/cjs/loader.js:934
  throw err;
  ^

Error: Cannot find module '/app/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Waiting for DB...
Waiting for DB...
.230910 03:06:13 mysqld_safe Logging to syslog.
230910 03:06:13 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
internal/modules/cjs/loader.js:934
  throw err;
  ^

Error: Cannot find module '/app/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```

**Comment by dialmaster** [comment]
Ah, I see. Well... The docker image, as is, already uses persistent storage
for everything, so I don't think you need to do any of that.

You should just be able to:
git clone the repo

Then run ./setup.sh (This is where you configure your output directory
(which is the local storage OUTSIDE the docker container where the videos
will be placed, I have this configured as one of my Plex video library
directories).

Then... just run ./start.sh, which will start the docker container up.

The database, thumbnail images and videos are all placed on the HOST server
via mounted volumes. There should be no need for using a
docker-compose.yml, as this was built.

See in ./start.sh:
docker run --name youtarr -d -v $youtubeOutputDirectory:/usr/src/app/data -v
/$(pwd)/server/images:/app/server/images -v /$(pwd)/config:/app/config -v
/$(pwd)/jobs:/app/jobs -v /$(pwd)/migrations:/app/migrations -v /$(pwd
)/database:/var/lib/mysql -p 3087:3011 -p 3321:3306 -e IN_DOCKER_CONTAINER=1
dialmaster/youtarr

**Comment by dialmaster** [comment]
Just to clarify -- I think all you would need to do is use
/mnt/rclone/TV/TV_Shows_YT as your directory name when you run
./setup.sh... based on the docker-compose.yml file you pasted above.

**Comment by nitschis** [comment]
Thank you for the reply, it seems really strange to me that I have to execute things on the host machine to get a docker container running. Shouldn't all that just happen in the container?

I got it to work with executing the setup/run once and then using a docker-compose file.
I can access it per direct connection and port. However, behind a Nginx reverse-proxy, I get the HTML output that JavaScript is not working or disabled.

**Comment by dialmaster** [comment]
The setup.sh script on the host machine simply sets some configuration
variables that are read by the docker process. It may seem a little strange
to you, but it's a pattern I've seen used elsewhere.

As far as accessing it behind a reverse proxy... that should work just
fine. I have something similar setup via apache, maybe my config (with some
redacted portions) would help you:

<VirtualHost *:80>
# replace with whatever your proxy hostname is)
    ServerName youtarr.myawesomeproxy.com

    RewriteEngine On
    RewriteCond %{HTTPS} !=on
    RewriteRule ^/(.*) https://%{SERVER_NAME}/$1 [R,L]
</VirtualHost>

<VirtualHost *:443>
# replace with whatever your proxy hostname is)
    ServerName  youtarr.myawesomeproxy.com

    SSLEngine on
    SSLCertificateFile "/opt/bitnami/apache2/conf/server.crt"
    SSLCertificateKeyFile "/opt/bitnami/apache2/conf/server.key"

# Replace all instances of 123.456.789.001 with the actual IP where your
youtarr instance is running

    ProxyPreserveHost On
    ProxyPass / http://123.456.789.001:3087/
    ProxyPassReverse / http://123.456.789.001:3087/

    RewriteEngine on
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteCond %{HTTP:Connection} upgrade [NC]
    RewriteRule .* "ws://123.456.789.001:3087%{REQUEST_URI}" [P]
</VirtualHost>

**Comment by nitschis** [comment]
> The setup.sh script on the host machine simply sets some configuration
> variables that are read by the docker process. It may seem a little strange
> to you, but it's a pattern I've seen used elsewhere.

Interesting, I have never come across this and it feels off to me personally. 


Thank you, after further digging the issue seems to be that no basedir is set. I am using a reverse proxy for a subdirectory (mydomain.com/youtarr), but youtarr is trying to execute on mydomain.com/.

Is there a way to set the base dir, I am not seeing a option for it in the config?

**Comment by dialmaster** [comment]
There is not currently any config option to set the basedir. You are
welcome to submit a PR for such a thing if you like and I will review/merge
it though :)

**Comment by nitschis** [comment]
I have changed to subdomain instead. However, the Plex login is not working at all, no matter if behind a reverse proxy or by direct IP.. I guess there is no way to directly set the X-Plex-Token?

**Comment by dialmaster** [comment]
As long as Youtarr is pointed at your Plex server, the Plex login should
work and the app with auth itself and get it's own API key.
You can get the Plex Server's IP Address/hostname in config/config.json

**Comment by dialmaster** [comment]
Youtarr has been updated to use a docker-compose file
